### ISSUE TITLE
好强大，想尝试一番可惜不用ghost 。

### ISSUE THREAD

**Issue by guugg** [acccco/zebra-editor-core#1]
不知道是否支持php

**Comment by baskinwind** [comment]
这个一个纯前端的项目哦，php 我不太了解。应该是可以用的。
https://cdn.jsdelivr.net/npm/zebra-editor-core
这个是一个完整的 js ，引入就可以使用了。
但是文档目前还没空写。😂

**Comment by baskinwind** [comment]
不过后续，可能会做推文的功能，看大家需不需要吧。
