### ISSUE TITLE
支持vue吗??

### ISSUE THREAD

**Issue by aircjm** [acccco/zebra-editor-core#4]

**Comment by baskinwind** [comment]
支持的，纯原生的库，React Vue Anglar 都可以用。

**Comment by aircjm** [comment]
> 支持的，纯原生的库，React Vue Anglar 都可以用。

这个有如何支持vue react的demo吗?? 非常感谢

**Comment by baskinwind** [comment]
https://github.com/acccco/zebra-editor-core/tree/master/dev
可以把项目 clone 下来，启动 npm run dev
这个就是完整的 demo

**Comment by aircjm** [comment]
> https://github.com/acccco/zebra-editor-core/tree/master/dev
> 可以把项目 clone 下来，启动 npm run dev
> 这个就是完整的 demo

非常感谢

**Comment by baskinwind** [comment]
不过目前文档，还没有时间写。先看看吧，应该是见名知义的。有什么看不懂的地方可以联系我~
WX 二维码:
![me](https://user-images.githubusercontent.com/12695799/95840432-b346dd80-0d76-11eb-9509-53aa1bed55a7.png)
